apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.postgres.service.name . }}
  labels:
    app: {{ tpl .Values.postgres.deployment.name . }}
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    app: {{ tpl .Values.postgres.deployment.name . }}
  type: {{ .Values.postgres.service.type }}