apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.keycloak.name }}
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: management
    port: 9990
    targetPort: 9990
  selector:
    app: keycloak
  type: {{ .Values.service.keycloak.type }}
