apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.app.domain }}`)
    middlewares:
      - name: https-redirect
        namespace: default
    services:
    - name: {{ .Values.service.keycloak.name }}
      port: 8080
  tls:
    secretName: {{ .Values.secrets.letsencrypt.secretName }}
