apiVersion: v1
kind: Secret
type: Opaque
data:
  KEYCLOAK_USER: {{ .Values.secrets.admin.KEYCLOAK_USER | b64enc }}
  KEYCLOAK_PASSWORD: {{ .Values.secrets.admin.KEYCLOAK_PASSWORD | b64enc }}
metadata:
  labels:
    app: keycloak
  name: {{ .Values.secrets.admin.secretName }}
