apiVersion: v1
kind: Secret
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.secrets.admin.KEYCLOAK_ADMIN | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.admin.KEYCLOAK_ADMIN_PASSWORD | b64enc }}
metadata:
  labels:
    app: keycloak
  name: {{ .Values.secrets.admin.secretName }}
