apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-api
  name: {{ .Release.Name }}-api
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}-api
