apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-manager
  name: {{ .Release.Name }}-manager
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - port: 8181
  selector:
    app: {{ .Release.Name }}-manager
