apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-proxy
  name: {{ .Release.Name }}-proxy
spec:
  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-proxy
