apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-settings-configmap
  labels:
    app: {{ .Release.Name }}-proxy
  annotations:
    helm.sh/hook: pre-install,post-delete
data:
  compress.conf: |
    gzip on;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 9;
    gzip_types text/plain text/css application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/x-icon image/vnd.microsoft.icon image/bmp image/svg+xml;

  logging.conf: |
    log_format json_combined escape=json
      '{'
        '"upstream_response_length": "$upstream_response_length",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"server_addr": "$server_addr",'
        '"server_port": "$server_port",'
        '"request_method": "$request_method",'
        '"http_referer": "$http_referer",'
        '"http_user_agent": "$http_user_agent",'
        '"http_x_forwarded_for": "$http_x_forwarded_for",'
        '"http_x_header": "$http_x_header",'
        '"nginx_version": "$nginx_version",'
        '"server_protocol": "$server_protocol",'
        '"request":"$request",'
        '"request_length": "$request_length",'
        '"request_time": "$request_time",'
        '"upstream_response_time": "$upstream_response_time",'
        '"request_host":"$host",'
        '"server_name": "$server_name",'
        '"remote_addr": "$remote_addr",'
        '"realip_remote_addr": "$realip_remote_addr",'
        '"http_status": "$status",'
        '"time_local":"$time_local",'
        '"time_iso8601":"$time_iso8601",'
        '"msec":"$msec",'
        '"upstream_addr": "$upstream_addr",'
        '"upstream_connect_time": "$upstream_connect_time",'
        '"upstream_response_time": "$upstream_response_time",'
        '"upstream_status": "$upstream_status",'
        '"uri": "$uri",'
        '"query_string": "$query_string",'
        '"remote_user": "$remote_user",'
        '"cookie_username": "$cookie_username",'
        '"upstream_header_time": "$upstream_header_time"'
      '}';

    access_log /var/log/external/nginx/access_json.log json_combined ;
    error_log  /var/log/external/nginx/error.log warn;

  orchestrator.conf: |
    server {
      listen 80;
      server_name {{ .Values.kasm.domain }};

      include /etc/nginx/conf.d/services.d/*.conf;
      include /etc/nginx/conf.d/containers.d/*.conf;

      client_max_body_size 1G;
      server_tokens off;

      # Hide error messages from upstream servers
      proxy_intercept_errors on;
      error_page 500 = @internal_error;
      location @internal_error {
        default_type "text/html";
        return 500 "<H1>Internal Error</H1>";
      }
    }

  orchestrator_http.conf: |
    server {
      listen 80;
      server_name {{ .Values.kasm.domain }};

      include /etc/nginx/conf.d/services.d/*.conf;
      include /etc/nginx/conf.d/containers.d/*.conf;

      client_max_body_size 1G;
      server_tokens off;

      # Hide error messages from upstream servers
      proxy_intercept_errors on;
      error_page 500 = @internal_error;
      location @internal_error {
          default_type "text/html";
          return 500 "<H1>Internal Error</H1>";
      }
    }

  upstream_kasm_api.conf: |
    upstream kasm-api {
      keepalive 64;
      server kasm-api:80;
    }

  upstream_kasm_manager.conf: |
    upstream kasm-manager {
      keepalive 64;
      server kasm-manager:8181;
    }

  # upstream_kasm_guac.conf: |
  #   upstream kasm_guac_backend {
  #     {{- $cluster_size := int .Values.kasm.deployment.guac.cluster_size }}
  #     {{- range $i := until $cluster_size }}
  #       server kasm-guac:{{ add 3001 $i }};
  #     {{- end }}
  #   }

  # upstream_kasm_proxy.conf: |
  #   upstream kasm-proxy {
  #     keepalive 64;
  #     server kasm-proxy:8080;
  #   }