apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-kasm-secrets
data:
  DEFAULT_MANAGER_TOKEN: {{ .Values.kasm.defaultManagerToken | b64enc }}
  DEFAULT_REGISTRATION_TOKEN: {{ .Values.kasm.defaultRegistrationToken | b64enc }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.kasm.defaultAdminPassword | b64enc }}
  DEFAULT_USER_PASSWORD: {{ .Values.kasm.defaultUserPassword | b64enc }}