app:
  configmap:
    homeserver:
      filename: homeserver.yaml
      name: matrix-synapse-homeserver-config
      oidc:
        client_id: synapse
        client_secret: ee999c8d-9b1c-43bb-832f-058b27d4b273
        enabled: true
        issuer: https://sso.eons.dev/auth/realms/StrangeDoor
      path: /synapse/config
    log:
      filename: my.matrix.host.log.config
      name: matrix-synapse-log-config
      path: /synapse/log
  deployment:
    affinity:
      podAffinity:
        labelSelectors:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - '{{ tpl (index .Values "postgres" "deployment" "name") .
                }}'
            topologyKey: kubernetes.io/hostname
    env:
      GID: 0
      UID: 0
    synapsePath:
      mountPath: /eons/local/{{ .Release.Namespace }}/{{ .Release.Name }}/app
      name: storage
      volumeMountPath: /synapse/data
    dataPath:
      mountPath: /eons/local/{{ .Release.Namespace }}/{{ .Release.Name }}/data
      name: storage
      volumeMountPath: /data
    image: matrixdotorg/synapse:v1.15.1-py3
    priorityClass: prod-low
    resources:
      limits:
        cpu: 4000m
        memory: 4000Mi
      requests:
        cpu: 500m
        memory: 1000Mi
  domain: matrix.eons.dev
postgres:
  deployment:
    affinity:
      nodeSelectors:
      - key: db
        value: sync1
    db:
      auth: password
      name: synapse
    hostPath:
      mountPath: /eons/local/{{ .Release.Namespace }}/{{ .Release.Name }}/pg-data
      name: pg-data
    image: postgres:12.4-alpine
    priorityClass: prod-low
    resources:
      limits:
        cpu: 4000m
        memory: 4000Mi
      requests:
        cpu: 500m
        memory: 1000Mi
  secrets:
    DB_PASSWORD: 5dn7KESNGaXD
    DB_USER: synapseuser
secrets:
  letsencrypt:
    issuer: letsencrypt
    kind: ClusterIssuer
    secretName: matrix-letsencrypt-cert
  signingKey:
    filename: my.matrix.host.signing.key
    keyValue: ed25519 a_ggLh nHlPj4JpV/I4hJwqPjZTCjeocwTGsmJriAv8V1k4wdo
    path: /synapse/keys
    secretName: matrix-synapse-signingkey-secret
service:
  matrix:
    name: matrix-svc
    type: ClusterIP
