apiVersion: v1
kind: Service
metadata:
  labels:
    app: matrix
  name: {{ .Values.service.matrix.name }}
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 8008
    name: http
  - port: 9000
    name: metrics
  selector:
    app: matrix