apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secrets.signingKey.secretName }}
data:
  {{ .Values.secrets.signingKey.filename }}: {{ .Values.secrets.signingKey.keyValue | b64enc }}
