# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: {{ tpl .Values.deployment.name . }}
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - kind: Rule
#     match: Host(`{{ .Values.domain }}`)
#     services:
#     - name: {{ tpl .Values.deployment.name . }}-service
#       port: 80
#   tls:
#     secretName: {{ tpl .Values.deployment.name . }}-cert
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: {{ tpl .Values.deployment.name . }}-80redirect
# spec:
#   entryPoints:
#     - web
#   routes:
#   - kind: Rule
#     match: Host(`{{ .Values.domain }}`)
#     middlewares:
#       - name: https-redirect
#         namespace: default
#     services:
#     - name: {{ tpl .Values.deployment.name . }}-service
#       port: 80
# ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ tpl .Values.deployment.name . }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    # nginx.ingress.kubernetes.io/proxy-body-size: 1g
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ tpl .Values.deployment.name . }}-service
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ tpl .Values.deployment.name . }}-cert