apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ tpl .Values.deployment.name . }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
    - name: {{ tpl .Values.deployment.name . }}-service
      port: 80
  tls:
    secretName: {{ tpl .Values.deployment.name . }}-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ tpl .Values.deployment.name . }}-80redirect
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    middlewares:
      - name: https-redirect
        namespace: default
    services:
    - name: {{ tpl .Values.deployment.name . }}-service
      port: 80
---