apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.deployment.name . }}-service
  labels:
    app: {{ tpl .Values.deployment.name . }}
spec:
 type: LoadBalancer
 externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: {{ tpl .Values.deployment.name . }}
