kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eons-admin-cr
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - get
      - list
      - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eons-admin-crb

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eons-admin-cr
subjects:
  - kind: ServiceAccount
    name: eons-admin-sa
    namespace: kube-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: kube-system
  name: eons-admin-sa