{{- range $p := $.Values.host.ports }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ tpl $.Values.host.name $ }}-{{ $p.name }}'
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: vm
    # cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: traefik
  rules:
  - host: {{ tpl $.Values.host.fqdn $ }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ tpl $.Values.host.name $ }}-svc
            port:
              number: {{ $p.port }}
  # tls:
  # - hosts:
  #   - {{ tpl $.Values.host.fqdn $ }}
  #   secretName: '{{ tpl $.Values.host.name $ }}-{{ $p.name }}-secret'
---
{{- end }}
