{{- range $p := $.Values.host.ports }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ tpl $.Values.host.name $ }}-{{ $p.name }}'
  # annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ tpl $.Values.host.name $ }}-svc
            port:
              number: {{ $p.port }}
  # tls:
  # - hosts:
  #   - {{ .Values.host.fqdn }}
  #   secretName: {{ .Values.secrets.letsencrypt.secretName }}
---
{{- end }}
