apiVersion: v1
kind: Service
metadata:
  name: "{{ tpl .Values.host.name . }}-svc"
spec:
  ports:
  {{- range .Values.host.ports }}
    - name: "{{ .name }}"
      port: {{ .port }}
      targetPort: {{ .port }}
  {{- end }}
  selector:
    vm.kubevirt.io/name: "{{ tpl .Values.host.name . }}"