apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ tpl .Values.host.name . }}"
  generation: 1
  labels:
    app: "{{ tpl .Values.host.name . }}"
    kubevirt.io/os: linux
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: "{{ tpl .Values.host.name . }}"
    spec:
      domain:
        devices:
          disks:
            - name: hostdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: "cloudinit"
              cdrom:
                bus: "sata"
                readonly: true
          interfaces:
            - name: "default"
              bridge: {}
              macAddress: {{ .Values.host.machine.mac }}
        machine:
          type: {{ .Values.host.machine.type }}
        resources:
          requests:
            memory: {{ .Values.host.resources.requests.memory }}
            cpu: {{ .Values.host.resources.requests.cpu }}
      networks:
        - name: "default"
          pod: {}
      volumes:
        # - hostDisk:
        #     capacity: 1Gi
        #     path: /fss/disk.img
        #     type: DiskOrCreate
        #   name: hostdisk
        - name: hostdisk
          hostDisk:
            path: "{{ .Values.host.hostpath }}/{{ tpl .Values.host.name . }}.img"
            type: DiskOrCreate
          # containerDisk:
          #   image: {{ .Values.host.image }}
        - name: "cloudinit"
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: "{{ tpl .Values.host.name . }}"
              users:
              - name: proto
                sudo: ['ALL=(ALL) NOPASSWD:ALL']
                groups: sudo
                shell: /bin/bash
              chpasswd:
                list: |
                  proto:toor
                  root:toor
                expire: False
        
