apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ tpl .Values.deployment.name . }}
spec:
  entryPoints:
    - tinc
  routes:
  - kind: Rule
    match: Host(`{{ .Values.deployment.domain }}`)
    services:
    - name: {{ tpl .Values.deployment.name . }}-service
      port: 655
