apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-n8n-svc
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - port: 5678
  selector:
    app: {{ .Release.Name }}
