apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-guac
  labels:
    app: {{ .Release.Name }}-guac
  annotations:
    helm.sh/hook: pre-install,post-delete
data:
  kasmguac.app.config.yaml: |
    kasmguac:
      id: {{ .Values.kasm.deployment.guac.id }}
      port: 3000
      cluster_size: {{ .Values.kasm.deployment.guac.cluster_size }}
      server_address: "{{ .Values.kasm.domain }}"
      server_port: 443
      zone: "remote"
      registration_token: {{ .Values.kasm.defaultRegistrationToken }}
      kasm_delete_session_watch_interval: 60
      recording:
        default_width: 1920
        default_height: 1080
        default_framerate: 12
        default_bitrate: 8
        retention_period_in_hours: 24
        encoding_queue_size: 2
        processing_interval: 30
        processing_cutoff: 30
        summary_interval: 300
        summary_include_intial_logs: true
      logging:
        errorEventName: error
        logDirectory: /opt/kasm/current/log/
        fileNamePattern: kasmguac-<DATE>.log
        dateFormat: YYYY.MM.DD
        timestampFormat: YYYY-MM-DD HH:mm:ss.SSS
    api:
      hostnames: ['{{ .Values.kasm.domain }}']
      port: 443
      allow_self_signed_cert: false
      hostname_refresh_interval: 30
      auth_token: {{ .Values.kasm.deployment.guac.auth_token }}