deployment:
  name: '{{ .Release.Name }}-host'
  domain: '{{ .Release.Name }}.{{ .Release.Namespace }}.vpn.infrastructure.tech'
  image: eons/img_tinc:latest
  tincPath: '/eons/local/tinc/{{ .Release.Namespace }}/{{ .Release.Name }}/host'
  priorityClass: prod-low
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 256Mi