apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.11.12.200-10.11.12.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vpn
  namespace: metallb-system