apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: element
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.app.domain }}`)
    services:
    - name: {{ .Values.service.name }}
      port: 80
  tls:
    secretName: {{ .Values.secrets.letsencrypt.secretName }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: element-80redirect
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.app.domain }}`)
    middlewares:
      - name: https-redirect
        namespace: default
    services:
    - name: {{ .Values.service.name }}-service
      port: 80
---