apiVersion: v1
kind: Service
metadata:
  labels:
    app: element
  name: {{ .Values.service.name }}
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - port: 80
  selector:
    app: element
