apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.name . }}
  labels:
    app: {{ tpl .Values.service.name . }}
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 5432
    protocol: TCP
  selector:
    app: {{ tpl .Values.deployment.name . }}
  type: {{ tpl .Values.service.type . }}