app:
  deployment:
    args: ["start-dev"] # Always use dev, since cert-manager handles SSL, etc.
    affinity:
      podAffinity:
        labelSelectors:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - '{{ tpl (index .Values "postgres" "postgres" "deployment"
                "name") . }}'
            topologyKey: kubernetes.io/hostname
    env:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres-svc:5432/keycloak
      KEYCLOAK_STATISTICS: all
    image: quay.io/keycloak/keycloak:24.0.1
    replicas: 1
  domain: CHANGEME
  url: https://CHANGEME
postgres:
  postgres:
    deployment:
      db:
        auth: password
        name: keycloak
      hostPath:
        mountPath: /cluster/{{ .Release.Namespace }}/{{ .Release.Name }}/pg-data
        name: pg-data
    secrets:
      DB_PASSWORD: CHANGEME
      DB_USER: keycloakuser
secrets:
  admin:
    KEYCLOAK_ADMIN_PASSWORD: CHANGEME
    KEYCLOAK_ADMIN: CHANGEME
    secretName: keycloak-admin-secret
  letsencrypt:
    issuer: letsencrypt
    kind: ClusterIssuer
    secretName: keycloak-letsencrypt-cert
service:
  keycloak:
    name: keycloak-svc
    type: ClusterIP
