kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cr
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - get
      - list
      - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-crb

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ $.Release.Namespace }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ .Release.Name }}-sa