apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  annotations:
    "helm.sh/hook": post-install
spec:
  redirectScheme:
    scheme: https
    permanent: true
