apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
    {{- range .Values.daemonset.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
    {{- end }}
  selector:
    app: {{ $.Release.Name }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
