apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.deployment.name . }}
  labels:
    app: {{ tpl .Values.deployment.name . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ tpl .Values.deployment.name . }}
  template:
    metadata:
      labels:
        app: {{ tpl .Values.deployment.name . }}
    spec:
      volumes:
        - name: {{ .Values.deployment.hostPath.name }}
          hostPath:
            path: {{ tpl .Values.deployment.hostPath.mountPath . }}
            type: DirectoryOrCreate
      containers:
        - name: postgres
          image: {{ .Values.deployment.image }}
          volumeMounts:
            - mountPath: {{ .Values.deployment.hostPath.volumeMountPath }}
              name: {{ .Values.deployment.hostPath.name }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: {{ tpl .Values.secrets.secretName . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: {{ tpl .Values.secrets.secretName . }}
            - name: POSTGRES_DB
              value: {{ .Values.deployment.db.name }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: {{ .Values.deployment.db.auth }}
          ports:
            - name: http
              containerPort: 5432
          resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
      {{- if .Values.deployment.priorityClass }}
      priorityClassName: {{ .Values.deployment.priorityClass }}
      {{- end }}
      {{- if .Values.deployment.affinity.nodeSelectors }}
      nodeSelector:
      {{- range .Values.deployment.affinity.nodeSelectors }}
        {{ .key }}: {{ .value }}
      {{- end }}
      {{- end }}