apiVersion: v1
kind: Secret
type: Opaque
data:
  NEXTCLOUD_ADMIN_USER: {{ .Values.secrets.nextcloudAdmin.NEXTCLOUD_ADMIN_USER | b64enc }}
  NEXTCLOUD_ADMIN_PASSWORD: {{ .Values.secrets.nextcloudAdmin.NEXTCLOUD_ADMIN_PASSWORD | b64enc }}
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Values.secrets.nextcloudAdmin.secretName }}
