apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Values.service.nextcloud.name }}
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}
