apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ tpl .Values.deployment.name . }}
  name: {{ tpl .Values.secrets.secretName . }}
  annotations:
    helm.sh/hook: pre-install
data:
  MYSQL_PASSWORD: {{ tpl .Values.secrets.password . | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ tpl .Values.secrets.rootpassword . | b64enc }}
  MYSQL_USER: {{ tpl .Values.secrets.user . | b64enc }}
