daemonset:
  args:
  - --api.insecure
  - --accesslog
  - --api.dashboard=true
  - --entryPoints.web.address=:80
  - --entryPoints.websecure.address=:443
  - --entryPoints.acme.address=:8089
  - --entryPoints.internal.address=:8081
  - --entryPoints.matrix-fed.address=:8448
  - --providers.kubernetescrd
  - --providers.kubernetesIngress=true
  - --providers.kubernetesIngress.ingressClass=traefik-cert-manager
  - --ping
  image: traefik:latest
  ports:
  - containerPort: 80
    name: web
  - containerPort: 443
    name: websecure
  - containerPort: 8080
    name: admin
  - containerPort: 8089
    name: acme
  - containerPort: 8081
    name: internal
  - containerPort: 8448
    name: matrix-fed
  serviceAccountName: traefik-ingress-controller
dashboard:
  entryPoints:
  - admin
  routes:
  - kind: Rule
    match: Host(`traefik`)
    services:
    - name: traefik
      port: 8080
service:
  loadBalancerIP: 10.4.4.1
