daemonset:
  args:
  - --api.insecure
  - --accesslog
  - --api.dashboard=true
  - --entryPoints.web.address=:80
  - --entryPoints.web.forwardedHeaders.insecure
  - --entryPoints.websecure.address=:443
  - --entryPoints.websecure.forwardedHeaders.insecure
  - --entryPoints.tinc.address=:655
  - --entryPoints.tinc.forwardedHeaders.insecure
#  - --entryPoints.admin.address=:8080
    # - --entryPoints.acme.address=:8089
  # - --entryPoints.internal.address=:8081
  # - --entryPoints.matrix-fed.address=:8448
  - --providers.kubernetescrd
  - --providers.kubernetesIngress=true
  - --providers.kubernetesIngress.ingressClass=traefik-cert-manager
  - --ping

  #NEED TO UPDATE CRDS FOR 2.5+
  # image: traefik:latest
  image: traefik:latest
  
  ports:
  - name: web
    containerPort: 80
    nodePort: 31080
  - name: websecure
    containerPort: 443
    nodePort: 31443
  - containerPort: 8080
    name: admin
  # - containerPort: 8089
  #   name: acme
  # - containerPort: 8081
  #   name: internal
  # - containerPort: 8448
  #   name: matrix-fed
  serviceAccountName: traefik-ingress-controller

dashboard:
#  entryPoints:
#  - admin
  routes:
  - kind: Rule
    match: Host(`traefik`)
    services:
    - name: traefik
      port: 8080

service:
  loadBalancerIP: 10.4.4.1
